MODULE1_COMMON_FILES 	+= module1/service/clockConfigService/if/clockConfigSrvIf.cc \
			   module1/service/clockConfigService/src/clockConfigSrv.cc

MODULE1_TARGET1_FILES	+= module1/service/clockConfigService/src/clockConfigSrvTarget1.cc	
