# --------------------------------------------------
# PATH DEFINITIONS
# --------------------------------------------------

# ROOT_DIR should be defined in sw/make/Makefile
SW_DIR 	= $(ROOT_DIR)/make-version/sw
APP_DIR = $(SW_DIR)/app
BIN_DIR = $(SW_DIR)/bin
OBJ_DIR = $(BIN_DIR)

DEPENDENCIES_MAP_FIXING	= (perl -pi -e 's,(?!/)$(<F),$<,;s, \.\./inc, $(<D)/../inc,g;s, ([a-zA-Z0-9_][-\./a-zA-Z0-9_]*\.[h|cc|txt]), $(<D)/$$1,g' $$D_FILE ; echo "\#FIX_DEP_MAP_MARKER" >> $$D_FILE)

TARGET1_CC	:= $(CC)
TARGET1_CXX	:= $(CXX)
RMV		:= rm -rf

all: test1

test1:
	@echo "I'm here in Makefile.config"
