

TARGET1_CFLAGS		:= \
		   	-Werror -Wno-psabi \
		   	-Wall -Wno-attributes -Wno-write-strings \
		   	-Wformat-security \
		  	-c -fno-omit-frame-pointer -pipe \
		   	-feliminate-unused-debug-types \
		   	-ffunction-sections -fdata-sections -fno-exceptions -std=c++17

all: common_Makefile

common_Makefile:
	@echo "sw/make/Makefile.common: Done!!! [OK]"
